"""restrict_client_fk_on_projects_requests_ai_interactions

Revision ID: 5a7fcaf651d6
Revises: 7dd0cae82323
Create Date: 2026-08-13 10:13:38.390373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7fcaf651d6'
down_revision: Union[str, Sequence[str], None] = '7dd0cae82323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_interactions_client_id_fkey'), 'ai_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'ai_interactions', 'clients', ['client_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('customer_requests_client_id_fkey'), 'customer_requests', type_='foreignkey')
    op.create_foreign_key(None, 'customer_requests', 'clients', ['client_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('projects_client_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_client_id_fkey'), 'projects', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'customer_requests', type_='foreignkey')
    op.create_foreign_key(op.f('customer_requests_client_id_fkey'), 'customer_requests', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ai_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('ai_interactions_client_id_fkey'), 'ai_interactions', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
