"""add_is_active_to_developers

Revision ID: 70ad4cede621
Revises: 04b0a99f35f5
Create Date: 2026-08-13 07:24:32.378349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ad4cede621'
down_revision: Union[str, Sequence[str], None] = '04b0a99f35f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developers', 'is_active')
    # ### end Alembic commands ###
