"""add_unique_active_project_per_client_index

Revision ID: 896296321246
Revises: ca88e7208136
Create Date: 2026-08-13 09:02:45.747218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896296321246'
down_revision: Union[str, Sequence[str], None] = 'ca88e7208136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_unique_active_project_per_client', 'projects', ['client_id'], unique=True, postgresql_where="status = 'active'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_active_project_per_client', table_name='projects', postgresql_where="status = 'active'")
    # ### end Alembic commands ###
