"""update_project_developer_ondelete_to_restrict

Revision ID: ca88e7208136
Revises: 70ad4cede621
Create Date: 2026-08-13 07:35:53.592277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca88e7208136'
down_revision: Union[str, Sequence[str], None] = '70ad4cede621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_developer_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key('projects_developer_id_fkey', 'projects', 'developers', ['developer_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_developer_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key('projects_developer_id_fkey', 'projects', 'developers', ['developer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
